series: 44
sp: 45
chan: 46
vdm: 47
authp: 48
plt: 49
vps: 50
adPod: 51
ppid: 52
refDomain: 53
distAssetId: 54
bundleId: 55
isDnt: 56
linearProvider: 57
metadata_sport: 58
dph: 59
sportSeriesName: 60
metadata_live: 62
device_os: 63
device_type: 64
metadata_assetId: 65
metadata_contenttype: 66
metadata_state: 67
metadata_suburb: 68
metadata_title: 69
metadata_woId: 70
userType: 71
excl_cat: 72
